CREATE TABLE users (
  id SERIAL PRIMARY KEY, 
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  admin BOOLEAN NOT NULL
);

CREATE TABLE topic (
  id SERIAL PRIMARY KEY,
  topic TEXT NOT NULL
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY, 
  question TEXT NOT NULL,
  topic_id INTEGER NOT NULL REFERENCES topic
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY, 
  option TEXT NOT NULL,
  correct BOOLEAN NOT NULL DEFAULT FALSE,
  question_id INTEGER NOT NULL REFERENCES questions
);

CREATE TABLE answers (
  id SERIAL PRIMARY KEY,
  option_id INTEGER NOT NULL REFERENCES options,
  user_id INTEGER NOT NULL REFERENCES users
);

CREATE TABLE quiz (
  id SERIAL PRIMARY KEY, 
  user_id INTEGER NOT NULL REFERENCES users,
  question INTEGER NOT NULL REFERENCES questions
);

INSERT INTO topic (
  topic
)
VALUES 
  ('Viihde'),
  ('Maantiede'),
  ('Pelit'),
  ('Kirjallisuus'),
  ('Luonto'),
  ('Urheilu'),
  ('Historia'),
  ('Taide'),
  ('Musiikki'),
  ('Luonnontiede');

INSERT INTO questions (
  question,
  topic_id
)
VALUES
  ('Kuka on ohjannut elokuvan Jurassic Park?', 1),
  ('Kuka on ohjannut elokuvan Terminator 2?', 1),
  ('Kuka näyttelijä näyttelee John Wickia samannimisessä elokuvassa?', 1),
  ('Kuka näyttelijä näyttelee Elliotia sarjassa Mr. Robot?', 1),
  ('Kuinka monta kautta Game of Thronesia tehtiin?', 1),
  ('Kuka ohjasi vuonna 1985 julkaistun Tuntematton sotilaan?', 1),
  ('Mikä on kautta aikain eniten tuottanut elokuva?', 1),
  ('Kuka on säveltänyt musiikit Star Wars -elokuviin?', 1),
  ('Minä vuonna Salatut Elämät tv-sarjan ensimmäinen jakso tuli ulos?', 1),
  ('Millä vuosikymmenellä Dallas-sarjan ensimmäinen jakso julkaistiin Yhdysvalloissa?', 1),
  ('Mikä on Marokon pääkaupunki?', 2),
  ('Mikä on Kanadan pääkaupunki?', 2),
  ('Kuinka monta miljoonaa asukasta Saksassa on?', 2),
  ('Kuinka monta miljoonaa asukasta Venäjällä on?', 2),
  ('Mikä näistä on pinta-alaltaan suurin maa?', 2),
  ('Mikä näistä on pinta-alaltaan suurin maa?', 2),
  ('Minkä maan kanssa Puola EI ole rajanaapuri?', 2),
  ('Minkä maan kanssa Belgia EI ole rajanaapuri?', 2),
  ('Mikä on Brasilian virallinen kieli?', 2),
  ('Mikä näistä EI ole yksi Sveitsin virallisista kielistä?', 2),
  ('Kuinka monta ruutua on shakkilaudassa?', 3),
  ('Kuinka monta Sattuma-ruutua Monopolissa on?', 3),
  ('Mikä pelitalo on kehittänyt Half-Life pelisarjan?', 3),
  ('Mikä pelitalo on julkaissut Zelda- pelisarjan?', 3),
  ('Mikä pokerikäsi näistä on arvoltaan suurin?', 3),
  ('Minkä arvoinen kuningas on blackjackissa?', 3),
  ('Minkä nimisellä hahmolla The Witcher -sarjassa pelataan?', 3),
  ('Mikä on järjestyksessään toinen kirjain kreikkalaisissa aakkosissa?', 4),
  ('Mihin maahan sijoittuu kirja Kolme muskettisoturia?', 4),
  ('Mikä eläin on Richard Bachin kirjassa esiintyvä Joonatan?', 4),
  ('Mitkä ovat kiellettyjä Fahrenheit 451 -kirjan kuvaamassa yhteiskunnassa?', 4),
  ('Kuka on kirjoittanut romaanin Rikos ja rangaistus?', 4),
  ('Mikä on Suomen kansalliseläin?', 5),
  ('Mikä on Suomen kansalliskukka?', 5),
  ('Minkä värisiä kirvat yleensä ovat?', 5),
  ('Kuinka suuri siipiväli valkpäämerikotkalla voi olla?', 5),
  ('Mikä eläin on kansainvälisen ympäristöjärjestön WWF:n logossa?', 5),
  ('Mistä maasta F1-kuljettaja Ayrton Senna oli kotoisin?', 6),
  ('Mikä maa voitti kultaa jääkiekossa Vancouverin olympialaisissa vuonna 2010?', 6),
  ('Kuinka monta F1 -maailmanmestaruutta Mika Häkkinen voitti urallaan?', 6),
  ('Kuinka monta kenttäpelaajaa jalkapallojoukkueella on kentällä ottelun alussa maalivahdin lisäksi?', 6),
  ('Kenellä jalkapalloilijalla on eniten Kultainen pallo -palkintoja?', 6),
  ('Minkä eläimen kanssa Hannibal ylitti alpit?', 7),
  ('Missä maassa muinainen Macchu Picchun kaupunki sijaitsee?', 7),
  ('Missä kaupungissa Franz Ferdinand murhattiin?', 7),
  ('Missä maassa Aleksanteri Suuri syntyi?', 7),
  ('Missä maassa sijaitsee Versaillesin palatsi?', 7),
  ('Kuka teki kuuluisia maalauksia riveihin järjestetyistä Coca-Cola pulloista?', 8),
  ('Minkä maalainen taiteilija Salvaror Dali oli?', 8),
  ('Minkä taidesuuntauksen yksi kehittäjistä Pablo Picasso oli?', 8),
  ('Kenen maalaus on Viimeinen ehtoollinen?', 8),
  ('Kenen maalaus on Haavoittunut enkeli?', 8),
  ('Mikä yhtyeen kappale on Vuonna 85?', 9),
  ('Minkä yhtyeen maailmanhitti oli Money for Nothing?', 9),
  ('Minkä maalainen yhtye The Killers on?', 9),
  ('Millä vuosikymmennellä Woodstock järjestettiin?', 9),
  ('Missä kaupungissa järjestetään Ilosaarirock?', 9),
  ('Mikä on kullan kemiallinen merkki?', 10),
  ('Mikä on hopean kemiallinen merkki?', 10),
  ('Kuka kehitti yleisen suhteellisuusteorian?', 10),
  ('Mikä on jaksollisen järjestelmän ensimmäinen alkuaine?', 10),
  ('Kuka kehitti AIV-rehun?', 10),
  ('Minkä värinen on Pikachun korvanpää?', 3),
  ('Minkä kotimaisen peliyhtiön tuotoksia Max Paynet ovat?', 3),
  ('Minkä värinen on Super Marion lakki?', 3),
  ('Mikä on ruotsalaispoliisi Wallanderin etunimi?', 4),
  ('Mitä Kalevalan sampo jauhoi rahan ja viljan lisäksi?', 4),
  ('Kuka hallitsi Rivendelliä Taru Sormusten Herroista -kirjoissa?', 4),
  ('Mikä on Harry Potterin isän nimi?', 4),
  ('Kuka on kirjoittanut kirjan Sapiens: Ihmisen lyhyt historia?', 4),
  ('Minkä sienen toinen nimi on kanttarelli?', 5),
  ('Mikä seuraavista on havupuun hedelmä?', 5),
  ('Mikä näistä lajeista on kuollut sukupuuttoon?', 5),
  ('Mikä näistä ei ole nisäkäs?', 5),
  ('Minkä värinen on hillan marja?', 5),
  ('Mikä laji ei kuulu kymmenotteluun?', 6),
  ('Mitä termiä käytetään, jos pelaaja lyö golfissa tuloksen yksi lyönti alle parin?', 6),
  ('Missä joukkueessa Sami Hyypiä voitti Mestarien liigan?', 6),
  ('Missä seurassa Teemu Selänne aloitti NHL-uransa?', 6),
  ('Montako rallin maailmanmestaruutta Marcus Grönhölm saavutti?', 6),
  ('Minä vuonna Kristoffer Kolumbus purjehti Amerikkaan?', 7),
  ('Kuka oli Suomen viides presidentti?', 7),
  ('Kuka oli antiikin Kreikassa viinin jumala?', 7),
  ('Minä vuonna Suomi julistautui itsenäiseksi?', 7),
  ('Mikä aloitti toisen maailmansodan?', 7),
  ('Kuka teki Daavid-veistoksen?', 8),
  ('Minkä maalainen taidemaalari Claude Monet oli?', 8),
  ('Kuka seuraavista ei ole kuuluisa taidemaalari?', 8),
  ('Minkä maalaamisesta Rembrandt oli erityisen kiinnostunut?', 8),
  ('Kuka lahjoitti Vapaudenpatsaan Yhdysvalloille?', 8),
  ('Kuka on säveltänyt konserton Neljä vuodenaikaa?', 9),
  ('Kuka on säveltänyt oopperan Taikahuilu?', 9),
  ('Kuka oli Leevi and the Leavingsin laulaja?', 9),
  ('Minkä maalainen yhtye on Måneskin?', 9),
  ('Minkä yhtyeen hitti on Californication?', 9),
  ('Millä vuosisadalla Alexander Fleming keksi penisilliinin?', 10),
  ('Minkä maalainen fyysikko Niels Bohr oli?', 10),
  ('Mikä on heksadesimaalijärjestelmän kantaluku?', 10),
  ('Mikä aiheuttaa vuoroveden?', 10),
  ('Miksi kutsutaan suorakulmaisen kolmion suoran kulman vastaista sivua?', 10);
  
INSERT INTO options (
  option,
  correct,
  question_id 
)
VALUES 
  ('Steven Spielberg', TRUE, 1),
  ('Christopher Nolan', FALSE, 1),
  ('James Cameron', FALSE, 1),
  ('John McTiernan', FALSE, 1),
  ('James Cameron', TRUE, 2),
  ('John McTiernan', FALSE, 2),
  ('Renny Harlin', FALSE, 2),
  ('David Zucker', FALSE, 2),
  ('Keanu Reeves', TRUE, 3),
  ('Christian Bale', FALSE, 3),
  ('Hugh Jackman', FALSE, 3),
  ('Chris Evans', FALSE, 3),
  ('Rami Malek', TRUE, 4),
  ('Martin Wallström', FALSE, 4),
  ('Tom Holland', FALSE, 4),
  ('James McAvoy', FALSE, 4),
  ('8', TRUE, 5),
  ('6', FALSE, 5),
  ('7', FALSE, 5),
  ('10', FALSE, 5),
  ('Rauni Mollberg', TRUE, 6),
  ('Edvin Laine', FALSE, 6),
  ('Jörn Donner', FALSE, 6),
  ('Matti Kassila', FALSE, 6),
  ('Avatar', TRUE, 7),
  ('Titanic', FALSE, 7),
  ('Leijonakuningas', FALSE, 7),
  ('Jurassic Park', FALSE, 7),
  ('John Williams', TRUE, 8),
  ('Hans Zimmer', FALSE, 8),
  ('Nicholas Hooper', FALSE, 8),
  ('Howard Shore', FALSE, 8),
  ('1999', TRUE, 9),
  ('1998', FALSE, 9),
  ('2003', FALSE, 9),
  ('2001', FALSE, 9),
  ('1970', TRUE, 10),
  ('1960', FALSE, 10),
  ('1980', FALSE, 10),
  ('1990', FALSE, 10),
  ('Rabat', TRUE, 11),
  ('Casablanca', FALSE, 11),
  ('Tanger', FALSE, 11),
  ('Marrakech', FALSE, 11),
  ('Ottawa', TRUE, 12),
  ('Vancouver', FALSE, 12),
  ('Toronto', FALSE, 12),
  ('Montreal', FALSE, 12),
  ('83', TRUE, 13),
  ('37', FALSE, 13),
  ('121', FALSE, 13),
  ('66', FALSE, 13),
  ('145', TRUE, 14),
  ('112', FALSE, 14),
  ('171', FALSE, 14),
  ('221', FALSE, 14),
  ('Kanada', TRUE, 15),
  ('Kiina', FALSE, 15),
  ('Yhdysvallat', FALSE, 15),
  ('Brasilia', FALSE, 15),
  ('Meksiko', TRUE, 16),
  ('Italia', FALSE, 16),
  ('Ranska', FALSE, 16),
  ('Valko-Venäjä', FALSE, 16),
  ('Unkari', TRUE, 17),
  ('Saksa', FALSE, 17),
  ('Ukraina', FALSE, 17),
  ('Valko-Venäjä', FALSE, 17),
  ('Sveitsi', TRUE, 18),
  ('Hollanti', FALSE, 18),
  ('Luxemburg', FALSE, 18),
  ('Ranska', FALSE, 18),
  ('Portugali', TRUE, 19),
  ('Espanja', FALSE, 19),
  ('Englanti', FALSE, 19),
  ('Ranska', FALSE, 19),
  ('Englanti', TRUE, 20),
  ('Ranska', FALSE, 20),
  ('Saksa', FALSE, 20),
  ('Italia', FALSE, 20),
  ('64', TRUE, 21),
  ('100', FALSE, 21),
  ('81', FALSE, 21),
  ('48', FALSE, 21),
  ('3', TRUE, 22),
  ('4', FALSE, 22),
  ('5', FALSE, 22),
  ('2', FALSE, 22),
  ('Valve', TRUE, 23),
  ('Blizzard', FALSE, 23),
  ('iD Software', FALSE, 23),
  ('Ubisoft', FALSE, 23),
  ('Nintendo', TRUE, 24),
  ('Sega', FALSE, 24),
  ('Konami', FALSE, 24),
  ('Square Enix', FALSE, 24),
  ('Väri', TRUE, 25),
  ('Suora', FALSE, 25),
  ('Kaksi paria', FALSE, 25),
  ('Kolmoset', FALSE, 25),
  ('10', TRUE, 26),
  ('13', FALSE, 26),
  ('5', FALSE, 26),
  ('15', FALSE, 26),
  ('Geralt', TRUE, 27),
  ('Roche', FALSE, 27),
  ('Letho', FALSE, 27),
  ('Vesemir', FALSE, 27),
  ('Beeta', TRUE, 28),
  ('Gamma', FALSE, 28),
  ('Delta', FALSE, 28),
  ('Epsilon', FALSE, 28),
  ('Ranskaan', TRUE, 29),
  ('Englantiin', FALSE, 29),
  ('Italiaan', FALSE, 29),
  ('Saksaan', FALSE, 29),
  ('Lokki', TRUE, 30),
  ('Susi', FALSE, 30),
  ('Valas', FALSE, 30),
  ('Karhu', FALSE, 30),
  ('Kirjat', TRUE, 31),
  ('Radiot', FALSE, 31),
  ('Televisiot', FALSE, 31),
  ('Tuolit', FALSE, 31),
  ('Fjodor Dostojevski', TRUE, 32),
  ('Leo Tolstoi', FALSE, 32),
  ('Mikhail Bulgakov', FALSE, 32),
  ('Nikolai Gogol', FALSE, 32),
  ('Karhu', TRUE, 33),
  ('Joutsen', FALSE, 33),
  ('Leijona', FALSE, 33),
  ('Susi', FALSE, 33),
  ('Kielo', TRUE, 34),
  ('Lupiini', FALSE, 34),
  ('Apila', FALSE, 34),
  ('Valkovuokko', FALSE, 34),
  ('Vihreitä', TRUE, 35),
  ('Punaisia', FALSE, 35),
  ('Valkoisia', FALSE, 35),
  ('Sinisiä', FALSE, 35),
  ('2,3 metriä', TRUE, 36),
  ('3,6 metriä', FALSE, 36),
  ('1,2 metriä', FALSE, 36),
  ('4,5 metriä', FALSE, 36),
  ('Panda', TRUE, 37),
  ('Koala', FALSE, 37),
  ('Tiikeri', FALSE, 37),
  ('Norsu', FALSE, 37),
  ('Brasilia', TRUE, 38),
  ('Espanja', FALSE, 38),
  ('Portugali', FALSE, 38),
  ('Ranska', FALSE, 38),
  ('Kanada', TRUE, 39),
  ('Yhdysvallat', FALSE, 39),
  ('Suomi', FALSE, 39),
  ('Ruotsi', FALSE, 39),
  ('2', TRUE, 40),
  ('1', FALSE, 40),
  ('0', FALSE, 40),
  ('4', FALSE, 40),
  ('10', TRUE, 41),
  ('8', FALSE, 41),
  ('12', FALSE, 41),
  ('14', FALSE, 41),
  ('Lionel Messi', TRUE, 42),
  ('Christiano Ronaldo', FALSE, 42),
  ('Marco van Basten', FALSE, 42),
  ('Zinedine Zidane', FALSE, 42),
  ('Norsu', TRUE, 43),
  ('Hevonen', FALSE, 43),
  ('Muuli', FALSE, 43),
  ('Alpakka', FALSE, 43),
  ('Peru', TRUE, 44),
  ('Brasilia', FALSE, 44),
  ('Argentiina', FALSE, 44),
  ('Chile', FALSE, 44),
  ('Sarajevossa', TRUE, 45),
  ('Wienissä', FALSE, 45),
  ('Pariisissa', FALSE, 45),
  ('Berliinissä', FALSE, 45),
  ('Makedonia', TRUE, 46),
  ('Kreikka', FALSE, 46),
  ('Persia', FALSE, 46),
  ('Italia', FALSE, 46),
  ('Ranska', TRUE, 47),
  ('Espanja', FALSE, 47),
  ('Portugali', FALSE, 47),
  ('Sveitsi', FALSE, 47),
  ('Andy Warhol', TRUE, 48),
  ('Yves Klein', FALSE, 48),
  ('Max Ernst', FALSE, 48),
  ('Jackson Pollock', FALSE, 48),
  ('Espanjalainen', TRUE, 49),
  ('Portugalilainen', FALSE, 49),
  ('Ranskalainen', FALSE, 49),
  ('Italialainen', FALSE, 49),
  ('Kubismin', TRUE, 50),
  ('Realismin', FALSE, 50),
  ('Ekspressionismin', FALSE, 50),
  ('Dadaismin', FALSE, 50),
  ('Leonardo Da Vincin', TRUE, 51),
  ('Rafaelin', FALSE, 51),
  ('Michelangelon', FALSE, 51),
  ('Pablo Picasson', FALSE, 51),
  ('Hugo Simbergin', TRUE, 52),
  ('Helene Schjerbeck', FALSE, 52),
  ('Akseli Gallen-Kallela', FALSE, 52),
  ('Albert Edelfelt', FALSE, 52),
  ('Eppu Normaali', TRUE, 53),
  ('Popeda', FALSE, 53),
  ('Raptori', FALSE, 53),
  ('Yö', FALSE, 53),
  ('Dire Straitsin', TRUE, 54),
  ('The Rolling Stonesin', FALSE, 54),
  ('The Whon', FALSE, 54),
  ('The Beatlesin', FALSE, 54),
  ('Yhdysvaltalainen', TRUE, 55),
  ('Englantilainen', FALSE, 55),
  ('Kanadalainen', FALSE, 55),
  ('Saksalainen', FALSE, 55),
  ('1960', TRUE, 56),
  ('1970', FALSE, 56),
  ('1980', FALSE, 56),
  ('1990', FALSE, 56),
  ('Joensuu', TRUE, 57),
  ('Helsinki', FALSE, 57),
  ('Turku', FALSE, 57),
  ('Riihimäki', FALSE, 57),
  ('Au', TRUE, 58),
  ('Pt', FALSE, 58),
  ('Kr', FALSE, 58),
  ('P', FALSE, 58),
  ('Ag', TRUE, 59),
  ('Au', FALSE, 59),
  ('Zn', FALSE, 59),
  ('Al', FALSE, 59),
  ('Albert Einstein', TRUE, 60),
  ('Stephen Hawking', FALSE, 60),
  ('Hermann Minkowski', FALSE, 60),
  ('Nils Bohr', FALSE, 60),
  ('Vety', TRUE, 61),
  ('Happi', FALSE, 61),
  ('Hiili', FALSE, 61),
  ('Kulta', FALSE, 61),
  ('Artturi Ilmari Virtanen', TRUE, 62),
  ('Marie Curie', FALSE, 62),
  ('Louis Pasteur', FALSE, 62),
  ('Linus Pauling', FALSE, 62),
  ('Musta', TRUE, 63),
  ('Keltainen', FALSE, 63),
  ('Ruskea', FALSE, 63),
  ('Punainen', FALSE, 63),
  ('Remedyn', TRUE, 64),
  ('Housemarquen', FALSE, 64),
  ('Rovion', FALSE, 64),
  ('Supercellin', FALSE, 64),
  ('Punainen', TRUE, 65),
  ('Sininen', FALSE, 65),
  ('Musta', FALSE, 65),
  ('Valkoinen', FALSE, 65),
  ('Kurt', TRUE, 66),
  ('Anders', FALSE, 66),
  ('Jonas', FALSE, 66),
  ('Mats', FALSE, 66),
  ('Suolaa', TRUE, 67),
  ('Pippuria', FALSE, 67),
  ('Vettä', FALSE, 67),
  ('Hopeaa', FALSE, 67),
  ('Elrond', TRUE, 68),
  ('Galadriel', FALSE, 68),
  ('Gandalf', FALSE, 68),
  ('Aragorn', FALSE, 68),
  ('James', TRUE, 69),
  ('Charles', FALSE, 69),
  ('Albus', FALSE, 69),
  ('Ronald', FALSE, 69),
  ('Yuval Noah Harari', TRUE, 70),
  ('Richard Dawkins', FALSE, 70),
  ('Echkart Tolle', FALSE, 70),
  ('Neil deGrasse Tyson', FALSE, 70),
  ('Keltavahvero', TRUE, 71),
  ('Kalvasvahvero', FALSE, 71),
  ('Suppilovahvero', FALSE, 71),
  ('Valevahvero', FALSE, 71),
  ('Käpy', TRUE, 72),
  ('Marja', FALSE, 72),
  ('Terho', FALSE, 72),
  ('Norkko', FALSE, 72),
  ('Dodo', TRUE, 73),
  ('Emu', FALSE, 73),
  ('Strutsi', FALSE, 73),
  ('Kasuaari', FALSE, 73),
  ('Valashai', TRUE, 74),
  ('Delfiini', FALSE, 74),
  ('Sinivalas', FALSE, 74),
  ('Kenguru', FALSE, 74),
  ('Kullankeltainen', TRUE, 75),
  ('Tummanpunainen', FALSE, 75),
  ('Valkoinen', FALSE, 75),
  ('Sinertävä', FALSE, 75),
  ('Moukarinheitto', TRUE, 76),
  ('Keihäänheitto', FALSE, 76),
  ('Seiväshyppy', FALSE, 76),
  ('100 metrin juoksu', FALSE, 76),
  ('Birdie', TRUE, 77),
  ('Eagle', FALSE, 77),
  ('Bogey', FALSE, 77),
  ('Doublebogey', FALSE, 77),
  ('Liverpool', TRUE, 78),
  ('Bayer Leverkusen', FALSE, 78),
  ('Chelsea', FALSE, 78),
  ('Manchester United', FALSE, 78),
  ('Winnipeg Jets', TRUE, 79),
  ('Anaheim Ducks', FALSE, 79),
  ('San Jose Sharks', FALSE, 79),
  ('Colorado Avalanche', FALSE, 79),
  ('2', TRUE, 80),
  ('4', FALSE, 80),
  ('5', FALSE, 80),
  ('6', FALSE, 80),
  ('1492', TRUE, 81),
  ('1592', FALSE, 81),
  ('1652', FALSE, 81),
  ('1702', FALSE, 81),
  ('Risto Ryti', TRUE, 82),
  ('Kyösti Kallio', FALSE, 82),
  ('Martti Ahtisaari', FALSE, 82),
  ('Urho Kekkonen', FALSE, 82),
  ('Dionysos', TRUE, 83),
  ('Demeter', FALSE, 83),
  ('Apollo', FALSE, 83),
  ('Zeus', FALSE, 83),
  ('1917', TRUE, 84),
  ('1927', FALSE, 84),
  ('1907', FALSE, 84),
  ('1897', FALSE, 84),
  ('Saksan hyökkäys Puolaan', TRUE, 85),
  ('Saksan hyökkäys Hollantiin', FALSE, 85),
  ('Englannin hyökkäys Saksaan', FALSE, 85),
  ('Ranskan hyökkäys Saksaan ', FALSE, 85),
  ('Michelangelo', TRUE, 86),
  ('Rafael', FALSE, 86),
  ('Botticelli', FALSE, 86),
  ('Caravaggio', FALSE, 86),
  ('Ranskalainen', TRUE, 87),
  ('Saksalainen', FALSE, 87),
  ('Sveitsiläinen', FALSE, 87),
  ('Venäläinen', FALSE, 87),
  ('Karl Otto Fazer', TRUE, 88),
  ('Eero Järnefelt', FALSE, 88),
  ('Hugo Simberg', FALSE, 88),
  ('Albert Edelfelt', FALSE, 88),
  ('Omakuvien', TRUE, 89),
  ('Tähtitaivaan', FALSE, 89),
  ('Metsien', FALSE, 89),
  ('Puistojen', FALSE, 89),
  ('Ranska', TRUE, 90),
  ('Saksa', FALSE, 90),
  ('Belgia', FALSE, 90),
  ('Englanti', FALSE, 90),
  ('Vivaldi', TRUE, 91),
  ('Beethoven', FALSE, 91),
  ('Mozart', FALSE, 91),
  ('Bach', FALSE, 91),
  ('Mozart', TRUE, 92),
  ('Sibelius', FALSE, 92),
  ('Beethoven', FALSE, 92),
  ('Verdi', FALSE, 92),
  ('Gösta Sundqvist', TRUE, 93),
  ('Atte Blom', FALSE, 93),
  ('Risto Paananen', FALSE, 93),
  ('Irwin Goodman', FALSE, 93),
  ('Italialainen', TRUE, 94),
  ('Tanskalainen', FALSE, 94),
  ('Ruotsalainen', FALSE, 94),
  ('Saksalainen', FALSE, 94),
  ('Red Hot Chili Peppersin', TRUE, 95),
  ('Nirvanan', FALSE, 95),
  ('Oasiksen', FALSE, 95),
  ('Deep Purplen', FALSE, 95),
  ('1900', TRUE, 96),
  ('1800', FALSE, 96),
  ('1700', FALSE, 96),
  ('1600', FALSE, 96),
  ('Tanskalainen', TRUE, 97),
  ('Ruotsalainen', FALSE, 97),
  ('Saksalainen', FALSE, 97),
  ('Hollantilainen', FALSE, 97),
  ('16', TRUE, 98),
  ('10', FALSE, 98),
  ('8', FALSE, 98),
  ('12', FALSE, 98),
  ('Kuun ja Auringon painovoima', TRUE, 99),
  ('Tuuli', FALSE, 99),
  ('Merivirrat', FALSE, 99),
  ('Vuodenajat', FALSE, 99),
  ('Hypotenuusaksi', TRUE, 100),
  ('Kateetiksi', FALSE, 100),
  ('Janaksi', FALSE, 100),
  ('Alaksi', FALSE, 100);
